### ISSUE TITLE
Accounting

### ISSUE THREAD

**Issue by saberraz** [kartoza/kalu#34]
Setting up paypall and link it with each company's bank account

**Comment by gubuntu** [comment]
@saberraz pls send me Lutra's bank details. You'll porbably also have to configure the paypal account from within your online banking interface too, once it's set up

**Comment by gubuntu** [comment]
A Paypal account can be linked to multiple bank accounts but a bank account can be linked to only one Paypal account. 

So if Lutra and Kartoza want separate Paypal accounts for non-Limosa business, these will have to be linked to separate bank accounts. 

I've set up a Kartoza business account in USD in Paypal (there isn't a ZAR option), waiting for it to be linked to our current account. 

@saberraz, one option is to also link Lutra's bank account to the Kartoza Paypal account. I can do that with your bank card details or you can do that via your electronic banking. If you do the latter you'll probably need my Paypal login (for which we should probably have a 'paypal@limosageo.com' identity?)

A second option is that Lutra set up a Paypal account in GBP and use that to accept all Limosa Paypal payments. Then Kartoza also links to that or just uses Lutra as a conduit. 

@gioman how are we going to integrate Paypal payments into our site - in your code? Let me know what you need. Have you done Paypal integration before?

A third option, down the line, is that a separate Limosa company sets up its own Paypal account.

**Comment by gioman** [comment]
If you want me to integrate paypal into the site you will have to allow me to study and test how to do it.

**Comment by saberraz** [comment]
@gubuntu, paypal@limosageo.com email is up and running. Shall we have a skype call and talk through both options.
